### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by dkrikun** [Srekel/the-debuginator#1]
Hi, can you please add some screenshots to understand basic look and feel?

**Comment by Srekel** [comment]
Ah yeah, I will! On my list to do. :) I guess you may have seen this blog post? It contains a little of that, though I aim to do something more in-depth.

https://medium.com/@Srekel/implementing-a-fuzzy-search-algorithm-for-the-debuginator-cacc349e6c55

**Comment by dkrikun** [comment]
Oh, cool :)

**Comment by Srekel** [comment]
I think the newly added gif and video should suffice! I could add more static images but they don't quite do it justice. :)
